name: Cora - Coverage Reporter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Running corabank/front-coverage-action    
    steps:
      - uses: actions/checkout@v3
      - uses: corabank/front-coverage-action/coverage@v0.0.2
        with:
          repositoryPath: ${{ vars.GITHUB_REPOSITORY }}
          reporterId: ${{ secrets.CC_TEST_REPORTER_ID }}
          coverageCommand: test:unit
