name: CodeClimate - Coverage
on:
  push:
    branches:
      - master
    tags:
      - "!*" # Do not execute on tags
  pull_request:
    branches:
      - master
    paths:
      - "!*.MD"
  workflow_dispatch:
jobs:
  coverage:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: ["16.x"]
    name: Test & Publish code coverage to CodeClimate
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn test:unit
      - uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          debug: true
          verifyDownload: true
          coverageLocations: |
            ${{github.workspace}}/*.lcov:lcov
