name: CodeClimate - Coverage
on:
  push:
    branches:
      - master
    tags:
      - "!*" # Do not execute on tags
  pull_request:
    branches:
      - master
    paths:
      - "!*.MD"
  workflow_dispatch:
jobs:
  coverage:
    name: Test & Publish code coverage to CodeClimate
    runs-on: ubuntu-latest
    steps:
      - uses: paambaati/codeclimate-action@v3.2.0        
        with:
          coverageCommand: npm run jest
          debug: true
          verifyDownload: true
          coverageLocations: |
            ${{github.workspace}}/*.lcov:lcov
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
